export const jobs = [
  {
    title: "Junior Front End Web Dev",
    description: "Web Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
];
