export const jobs = [
  {
    id: 1,
    title: "Junior Front End Web Dev",
    description: "Web Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    id: 2,
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    id: 3,
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    id: 4,
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    id: 5,
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    id: 6,
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
  {
    id: 7,
    title: "Senior React Native Dev",
    description: "Mobile App Development",
    company: "Web Dev TM",
    location: "Liverpool",
    hours: 40,
    imgSrc: "/src/assets/placeholder.png",
  },
];
